version: '2.2'
services:
  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    ports:
      - "127.0.0.1:8088:80"
    depends_on:
      - account
      - dots
      - buildtrack

  account:
    build:
      context: account/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
    - ./account/:/app
    command: 'python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - accountdb
      - rabbitmq

  account_consumer:
    build:
      context: account/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./account/:/app
    command: 'python manage.py dot_consumer'
    depends_on:
      - account

  dots:
    build:
      context: dotstracks/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./dotstracks/:/app
    command: 'python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - dotsdb
      - rabbitmq
      - redis

  dots_consumer:
    build:
      context: dotstracks/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./dotstracks/:/app
    command: 'python manage.py account_consumer'
    depends_on:
      - dots

  buildtrack:
    build:
      context: generatetrack/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./generatetrack/:/app
    command: 'python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - dots
      - redis

  accountdb:
    image: mysql:5.7.22
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${ACCOUNT_DB_NAME}
      MYSQL_USER: ${ACCOUNT_DB_LOGIN}
      MYSQL_PASSWORD: ${ACCOUNT_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ACCOUNT_DB_PASSWORD}
    volumes:
      - ./database/accountdb/:/var/lib/mysql
    ports:
      - 127.0.0.1:33066:3306

  dotsdb:
    image: postgis/postgis
    restart: always
    env_file:
      - ".env"
    environment: # will be used by the init script
        LC_ALL: C.UTF-8
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        TZ: ${TZ}
    ports:
    - 127.0.0.1:5432:5432
    volumes:
    - ./database/dotsdb/:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq
    restart: always

  redis:
    image: redis
    restart: always