# Generated by Django 3.2.5 on 2021-07-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
