# Generated by Django 3.2.5 on 2021-07-16 09:15

import data.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_track_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='dots',
            field=data.models.DotsOrderedManyToManyField(to='data.Dot'),
        ),
    ]
